name: CI/CD Pipeline for Lab6

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'Lab6.CI-CD/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Lab6.CI-CD/**'

defaults:
  run:
    working-directory: Lab6.CI-CD

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('Lab6.CI-CD/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Checkstyle
        run: mvn checkstyle:check || echo "Checkstyle report created"

      - name: Build JAR package
        run: mvn clean package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: Lab6-CI-CD-jar
          path: target/*.jar
